const User = require('../models/User');
// Get all users
exports.getusers = async (req, res) => {
  try {
    const users = await User.find(); // fetch all users
    res.status(200).json(users); // send them as JSON
  } catch (error) {
    res.status(500).json({ message: 'Server error', error });
  }
};

// Register a new user
exports.registerUser = async (req, res) => {
  try {
    const { name, phone, email, password } = req.body;

    // Check if user already exists
    const existingUser = await User.findOne({ email });
    if (existingUser) return res.status(400).json({ message: 'User already exists' });

    const user = await User.create({ name, phone, email, password });
    res.status(201).json({
      message: 'User registered successfully',
      user: {
        _id: user._id, // This is auto-generated by MongoDB
        name: user.name,
        email: user.email,
        phone: user.phone,
      },
    });
  } catch (error) {
    res.status(500).json({ message: 'Server error', error });
  }
};

// Login user
exports.loginUser = async (req, res) => {
  try {
    const { email, password } = req.body;

    const user = await User.findOne({ email });
    if (!user) return res.status(404).json({ message: 'User not found' });

    const isMatch = await user.matchPassword(password);
    if (!isMatch) return res.status(400).json({ message: 'Invalid password' });

    res.status(200).json({
      message: 'Login successful',
      user: {
        _id: user._id,
        name: user.name,
        email: user.email,
        phone: user.phone,
      },
    });
  } catch (error) {
    res.status(500).json({ message: 'Server error', error });
  }
};
